ALTER TABLE item DROP COLUMN type;
ALTER TABLE item ADD COLUMN food_type BIGSERIAL;
ALTER TABLE item ADD CONSTRAINT food_type_fk FOREIGN KEY (food_type) REFERENCES type (id);
ALTER TABLE item ALTER COLUMN brand DROP NOT NULL;